import assert from 'node:assert/strict'
import { mkdtempSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import test from 'node:test'
process.env.NODE_ENV='test'; process.env.SKIP_DB_SEED='1'; process.env.JWT_SECRET='academic-workflow-test-secret-long-enough'; process.env.DATABASE_PATH=path.join(mkdtempSync(path.join(tmpdir(),'csit-academic-')),'test.sqlite')
const { db } = await import('../src/data/database.js'); const { default: app } = await import('../src/app.js'); const { hashPassword } = await import('../src/services/password.service.js'); const { seedCurriculum } = await import('../src/data/curriculumSeed.js')
for(const [id,name,role] of [['u1','student','USER'],['u2','other','USER'],['a1','admin','ADMIN']]) db.prepare('INSERT INTO users(id,username,email,password,role) VALUES(?,?,?,?,?)').run(id,name,`${name}@test.local`,hashPassword('Test@1234'),role)
seedCurriculum(db); seedCurriculum(db)
const database=db.prepare("SELECT id FROM courses WHERE code='273255'").get(); const mining=db.prepare("SELECT id FROM courses WHERE code='273375'").get()
for(const [id,name] of [['ta','Teacher A'],['tb','Teacher B'],['tc','Teacher C'],['td','Teacher D']]) db.prepare('INSERT INTO instructors(id,name,normalized_name,active) VALUES(?,?,?,1)').run(id,name,name.toLowerCase())
for(const [id,year,term] of [['db-1','2569','1'],['db-2','2569','2']]) db.prepare('INSERT INTO course_offerings(id,course_id,academic_year,semester,section) VALUES(?,?,?,?,?)').run(id,database.id,year,term,'')
db.prepare("INSERT INTO course_offering_teachers VALUES('db-1','ta',CURRENT_TIMESTAMP)").run(); db.prepare("INSERT INTO course_offering_teachers VALUES('db-1','tb',CURRENT_TIMESTAMP)").run(); db.prepare("INSERT INTO course_offering_teachers VALUES('db-2','tc',CURRENT_TIMESTAMP)").run()
const server=app.listen(0); const base=`http://127.0.0.1:${server.address().port}/api`; test.after(()=>{server.close();db.close()})
async function api(url,{method='GET',token,body}={}){const response=await fetch(base+url,{method,headers:{...(token?{authorization:`Bearer ${token}`} :{}),...(body?{'content-type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const text=await response.text();return{status:response.status,data:text?JSON.parse(text):null}}
async function login(user,password='Test@1234'){return (await api('/auth/login',{method:'POST',body:{usernameOrEmail:user,password}})).data.accessToken}
test('curriculum seed is repeatable and carries verified bilingual metadata',()=>{assert.equal(db.prepare("SELECT COUNT(*) count FROM courses WHERE code='273255'").get().count,1);const row=db.prepare("SELECT * FROM courses WHERE code='273255'").get();assert.equal(row.name_en,'Database Systems for Information Technology');assert.match(row.name_th,/ฐานข้อมูล/);assert.equal(row.credits,3)})
test('dependent teacher lookup filters exact course/year/semester and supports team teaching',async()=>{const token=await login('student');const first=await api(`/catalog/courses/${database.id}/teachers?year=2569&semester=1`,{token});assert.deepEqual(first.data.teachers.map(t=>t.name),['Teacher A','Teacher B']);const second=await api(`/catalog/courses/${database.id}/teachers?year=2569&semester=2`,{token});assert.deepEqual(second.data.teachers.map(t=>t.name),['Teacher C']);const empty=await api(`/catalog/courses/${mining.id}/teachers?year=2569&semester=1`,{token});assert.deepEqual(empty.data.teachers,[])})
test('suggestion stays pending until transactional admin approval creates the official assignment',async()=>{const user=await login('student');const admin=await login('admin');const suggestion=await api('/teacher-suggestions',{method:'POST',token:user,body:{teacherName:'Teacher X',courseId:mining.id,academicYear:'2569',semester:'1'}});assert.equal(suggestion.status,201);assert.equal(db.prepare("SELECT COUNT(*) count FROM instructors WHERE normalized_name='teacher x'").get().count,0);const duplicate=await api('/teacher-suggestions',{method:'POST',token:user,body:{teacherName:' Teacher   X ',courseId:mining.id,academicYear:'2569',semester:'1'}});assert.equal(duplicate.status,409);assert.equal((await api(`/admin/teacher-suggestions/${suggestion.data.id}`,{method:'PATCH',token:user,body:{approve:true}})).status,403);const approved=await api(`/admin/teacher-suggestions/${suggestion.data.id}`,{method:'PATCH',token:admin,body:{approve:true}});assert.equal(approved.data.status,'APPROVED');const available=await api(`/catalog/courses/${mining.id}/teachers?year=2569&semester=1`,{token:user});assert.deepEqual(available.data.teachers.map(t=>t.name),['Teacher X']);assert.deepEqual(db.prepare('PRAGMA foreign_key_check').all(),[])})
test('upload permits no teacher but rejects a teacher outside the exact offering',async()=>{const user=await login('student');const basePayload={title:'Secure metadata',fileName:'secure.txt',fileType:'text/plain',fileData:Buffer.from('secure academic metadata').toString('base64'),courseId:database.id,documentType:'Sheet',academicYear:'2569',semester:'1'};const optional=await api('/upload-requests',{method:'POST',token:user,body:basePayload});assert.equal(optional.status,201);assert.equal(optional.data.instructorId,'');const valid=await api('/upload-requests',{method:'POST',token:user,body:{...basePayload,title:'Teacher A material',fileData:Buffer.from('different secure data').toString('base64'),instructorId:'ta'}});assert.equal(valid.status,201);assert.equal(valid.data.courseOfferingId,'db-1');const wrongTerm=await api('/upload-requests',{method:'POST',token:user,body:{...basePayload,title:'Tampered teacher',fileData:Buffer.from('tampered secure data').toString('base64'),instructorId:'tc'}});assert.equal(wrongTerm.status,400);assert.match(wrongTerm.data.message,/not assigned/)})
test('context course search ranks codes and upload retains multiple verified teachers plus description',async()=>{const token=await login('student');const search=await api('/catalog/courses?q=2732&program=IT&year=2569&semester=1',{token});assert.equal(search.status,200);assert.equal(search.data.courses[0].code,'273255');const payload={title:'Team taught database',description:'  ER Diagram and Normalization  ',fileName:'team.txt',fileType:'text/plain',fileData:Buffer.from('team taught database unique').toString('base64'),programId:'program-it',courseId:database.id,documentType:'Sheet',academicYear:'2569',semester:'1',instructorIds:['ta','tb']};const created=await api('/upload-requests',{method:'POST',token,body:payload});assert.equal(created.status,201);assert.equal(created.data.description,'ER Diagram and Normalization');assert.deepEqual(created.data.teachers.map(item=>item.name),['Teacher A','Teacher B'])})
test('document-only teacher approval publishes attribution without changing canonical offering',async()=>{const user=await login('student');const admin=await login('admin');const suggestion=await api('/teacher-suggestions',{method:'POST',token:user,body:{teacherName:'Teacher D',courseId:database.id,academicYear:'2569',semester:'1',note:'co-teacher'}});assert.equal(suggestion.data.suggestionType,'EXISTING_TEACHER_NEW_ASSIGNMENT');const upload=await api('/upload-requests',{method:'POST',token:user,body:{title:'Document scoped teacher',fileName:'scope.txt',fileType:'text/plain',fileData:Buffer.from('document scope unique').toString('base64'),programId:'program-it',courseId:database.id,documentType:'Sheet',academicYear:'2569',semester:'1',suggestionIds:[suggestion.data.id]}});assert.equal(upload.status,201);assert.equal(upload.data.teacherSuggestions.length,1);assert.equal((await api(`/admin/upload-requests/${upload.data.id}/approve`,{method:'PATCH',token:admin,body:{}})).status,200);const reviewed=await api(`/admin/teacher-suggestions/${suggestion.data.id}`,{method:'PATCH',token:admin,body:{decision:'APPROVE_DOCUMENT'}});assert.equal(reviewed.data.approvalScope,'APPROVE_DOCUMENT');assert.equal(db.prepare("SELECT COUNT(*) count FROM course_offering_teachers WHERE offering_id='db-1' AND teacher_id='td'").get().count,0);assert.equal(db.prepare("SELECT COUNT(*) count FROM document_teachers WHERE display_name='Teacher D'").get().count,1)})
test('admin teacher and offering endpoints validate authorization and avoid duplicate offerings',async()=>{const user=await login('student');const admin=await login('admin');assert.equal((await api('/admin/teachers',{token:user})).status,403);const created=await api('/admin/teachers',{method:'POST',token:admin,body:{name:'Managed Teacher',email:'managed@nu.ac.th'}});assert.equal(created.status,201);const payload={courseId:database.id,academicYear:'2569',semester:'1',section:'2',teacherIds:[created.data.id,'ta','ta']};assert.equal((await api('/admin/course-offerings',{method:'PUT',token:admin,body:payload})).status,200);assert.equal((await api('/admin/course-offerings',{method:'PUT',token:admin,body:{...payload,teacherIds:[created.data.id]}})).status,200);assert.equal(db.prepare("SELECT COUNT(*) count FROM course_offerings WHERE course_id=? AND academic_year='2569' AND semester='1' AND section='2'").get(database.id).count,1);assert.equal(db.prepare("SELECT COUNT(*) count FROM course_offering_teachers WHERE offering_id=(SELECT id FROM course_offerings WHERE course_id=? AND section='2')").get(database.id).count,1);const inactive=await api(`/admin/teachers/${created.data.id}`,{method:'PATCH',token:admin,body:{active:false}});assert.equal(inactive.data.active,false)})
