<script setup>
import { onMounted, ref } from 'vue'; import { useRoute } from 'vue-router'; import { documentApi, downloadDocumentBlob, openDocumentBlob } from '@/services/document.service'; import DocumentImpactActions from '@/components/user/DocumentImpactActions.vue'; import { documentTypeLabel } from '@/services/terminology'
const props = defineProps({ documentType: { type: String, default: '' } }); const route = useRoute(); const data = ref(null); const error = ref(''); const busy = ref('')
async function load() { data.value = await documentApi.courseYear(route.params.courseId, route.params.year, props.documentType) }
onMounted(async () => { try { await load() } catch { error.value = 'โหลดเอกสารไม่สำเร็จ' } })
async function view(document) { busy.value = document.id; try { openDocumentBlob((await documentApi.view(document)).blob); await load() } catch { error.value = 'เปิดเอกสารไม่สำเร็จ' } finally { busy.value = '' } }
async function download(document) { busy.value = document.id; try { downloadDocumentBlob((await documentApi.download(document)).blob, document.fileName); await load() } catch { error.value = 'ดาวน์โหลดไม่สำเร็จ' } finally { busy.value = '' } }
async function helpful(document) { busy.value = document.id; try { const state = await documentApi.helpful(document, !document.helpfulByMe); document.helpfulByMe = state.helpful; document.helpfulCount = state.helpfulCount } catch (caught) { error.value = caught.message } finally { busy.value = '' } }
</script>
<template><section class="page-panel"><p v-if="error" class="form-error">{{ error }}</p><div v-if="!data" class="loading-state">กำลังโหลดภาคเรียน…</div><template v-else><div class="panel__header"><div><p class="eyebrow">{{ data.course.code }}</p><h1>{{ data.course.name }}</h1><p>ปีการศึกษา {{ data.academicYear }}</p></div></div><section v-for="group in data.semesters" :key="group.semester" class="semester-section"><div class="section-heading"><h2>ภาคเรียนที่ {{ group.semester }}</h2><span class="count-pill">{{ group.documentCount }} รายการ</span></div><div class="request-list"><article v-for="document in group.documents" :key="`${document.documentType}-${document.id}`" class="request-card document-card"><div class="request-card__main"><span class="type-chip">{{ documentTypeLabel(document.documentType) }}</span><h3>{{ document.title }}</h3><p v-if="document.description" class="document-description-preview">{{ document.description }}</p><p>{{ document.programName || 'ไม่ระบุสาขา' }} · ผู้สอน: {{ document.instructor || 'ยังไม่ทราบอาจารย์' }}</p></div><DocumentImpactActions :document="document" :busy="busy === document.id" @view="view(document)" @download="download(document)" @helpful="helpful(document)" /></article></div></section><div v-if="!data.semesters.length" class="empty-state"><h2>ยังไม่มีเอกสารที่เผยแพร่</h2></div></template></section></template>
