<script setup>
import { ref } from 'vue'
import { documentApi, downloadDocumentBlob, openDocumentBlob } from '@/services/document.service'
const query = ref(''); const documents = ref([]); const loading = ref(false); const error = ref(''); const searched = ref(false)
async function search() { loading.value = true; error.value = ''; try { documents.value = (await documentApi.search(query.value)).documents; searched.value = true } catch (_error) { error.value = 'Unable to search documents.' } finally { loading.value = false } }
async function view(document) { try { openDocumentBlob((await documentApi.view(document)).blob) } catch (_error) { error.value = 'Unable to preview the file.' } }
async function download(document) { try { downloadDocumentBlob((await documentApi.download(document)).blob, document.fileName) } catch (_error) { error.value = 'Unable to download the file.' } }
</script>
<template><section class="page-panel"><p class="eyebrow">Published library</p><h1>Search Documents</h1><form class="filter-bar" @submit.prevent="search"><input v-model="query" type="search" placeholder="Title, filename, course, year, or semester" /><button class="button button--primary" :disabled="loading">{{ loading ? 'Searching...' : 'Search' }}</button></form><p v-if="error" class="form-error">{{ error }}</p><div v-if="documents.length" class="request-list"><article v-for="document in documents" :key="`${document.documentType}-${document.id}`" class="request-card"><div class="request-card__main"><span class="status status--approved">{{ document.documentType }}</span><h2>{{ document.title }}</h2><p>{{ document.courseCode }} · {{ document.courseName }} · {{ document.academicYear }} · Semester {{ document.semester }}</p></div><div class="table-actions"><RouterLink class="button button--ghost" :to="`/dashboard/courses/${document.courseId}/years/${document.academicYear}`">Course</RouterLink><button class="button button--ghost" @click="view(document)">View</button><button class="button button--primary" @click="download(document)">Download</button></div></article></div><div v-else-if="searched" class="empty-state"><h2>No published documents found</h2></div></section></template>
