<script setup>
import { onMounted, ref } from 'vue'; import { documentApi, downloadDocumentBlob, openDocumentBlob } from '@/services/document.service'; import DocumentImpactActions from '@/components/user/DocumentImpactActions.vue'; import { documentTypeLabel } from '@/services/terminology'
const props = defineProps({ documentType: { type: String, required: true }, basePath: { type: String, required: true } }); const courses = ref([]); const results = ref([]); const query = ref(''); const loading = ref(true); const searching = ref(false); const error = ref(''); const searched = ref(false); const busy = ref('')
onMounted(loadCourses); async function loadCourses() { loading.value = true; error.value = ''; try { courses.value = await documentApi.courses(props.documentType) } catch { error.value = 'โหลดคลังเอกสารไม่สำเร็จ' } finally { loading.value = false } }
async function search() { if (!query.value.trim()) return; searching.value = true; error.value = ''; try { results.value = (await documentApi.search(query.value, props.documentType)).documents; searched.value = true } catch { error.value = 'ค้นหาไม่สำเร็จ' } finally { searching.value = false } }
async function view(document) { busy.value = document.id; try { openDocumentBlob((await documentApi.view(document)).blob); await search() } catch { error.value = 'เปิดเอกสารไม่สำเร็จ' } finally { busy.value = '' } }
async function download(document) { busy.value = document.id; try { downloadDocumentBlob((await documentApi.download(document)).blob, document.fileName); await search() } catch { error.value = 'ดาวน์โหลดไม่สำเร็จ' } finally { busy.value = '' } }
async function helpful(document) { busy.value = document.id; try { const state = await documentApi.helpful(document, !document.helpfulByMe); document.helpfulByMe = state.helpful; document.helpfulCount = state.helpfulCount } catch (caught) { error.value = caught.message } finally { busy.value = '' } }
</script>
<template><section class="page-panel"><div class="panel__header"><div><p class="eyebrow">Learning resources</p><h1>{{ documentTypeLabel(documentType) }}</h1><p>สำรวจตามรายวิชา ปีการศึกษา และภาคเรียน หรือค้นหาเฉพาะคลังนี้</p></div><span v-if="!loading" class="count-pill">{{ courses.length }} วิชา</span></div><form class="filter-bar" role="search" @submit.prevent="search"><label class="sr-only" for="catalog-search">ค้นหาเอกสาร</label><input id="catalog-search" v-model="query" type="search" :placeholder="`ค้นหา${documentTypeLabel(documentType)}`" /><button class="button button--primary" :disabled="searching">{{ searching ? 'กำลังค้นหา…' : 'ค้นหา' }}</button></form><p v-if="error" class="form-error">{{ error }}</p><div v-if="loading" class="loading-state">กำลังโหลดรายวิชา…</div><template v-else><div v-if="searched && results.length" class="request-list search-results"><article v-for="document in results" :key="document.id" class="request-card document-card"><div class="request-card__main"><span class="type-chip">{{ documentTypeLabel(document.documentType) }}</span><h2>{{ document.title }}</h2><p>{{ document.courseCode }} · ปี {{ document.academicYear }} · เทอม {{ document.semester }}</p></div><DocumentImpactActions :document="document" :busy="busy === document.id" @view="view(document)" @download="download(document)" @helpful="helpful(document)" /></article></div><div v-else-if="searched" class="empty-state empty-state--compact"><h2>ไม่พบเอกสาร</h2><p>ลองเปลี่ยนคำค้นหรือเลือกดูตามรายวิชา</p></div><div class="catalog-grid"><article v-for="course in courses" :key="course.id" class="material-card"><div class="material-card__top"><span class="material-type">{{ course.code }}</span><span>{{ course.documentCount }} เอกสาร</span></div><h2>{{ course.name }}</h2><p>{{ course.description }}</p><RouterLink class="text-link" :to="`${basePath}/${course.id}`">ดูรายวิชา →</RouterLink></article></div><div v-if="!courses.length && !searched" class="empty-state"><h2>ยังไม่มีเอกสารประเภทนี้</h2><button class="button button--ghost" @click="loadCourses">ลองอีกครั้ง</button></div></template></section></template>
