<script setup>
import { onMounted, ref } from 'vue'
import { documentApi, downloadDocumentBlob, openDocumentBlob } from '@/services/document.service'

const props = defineProps({ documentType: { type: String, required: true }, basePath: { type: String, required: true } })
const courses = ref([]); const results = ref([]); const query = ref(''); const loading = ref(true); const searching = ref(false); const error = ref(''); const searched = ref(false)
onMounted(loadCourses)
async function loadCourses() { loading.value = true; error.value = ''; try { courses.value = await documentApi.courses(props.documentType) } catch (_error) { error.value = `Unable to load ${props.documentType.toLowerCase()} files.` } finally { loading.value = false } }
async function search() { searching.value = true; error.value = ''; try { results.value = (await documentApi.search(query.value, props.documentType)).documents; searched.value = true } catch (_error) { error.value = `Unable to search ${props.documentType.toLowerCase()} files.` } finally { searching.value = false } }
async function view(document) { try { openDocumentBlob((await documentApi.view(document)).blob) } catch (_error) { error.value = 'Unable to preview the file.' } }
async function download(document) { try { downloadDocumentBlob((await documentApi.download(document)).blob, document.fileName) } catch (_error) { error.value = 'Unable to download the file.' } }
</script>
<template><section class="page-panel"><div class="panel__header"><div><p class="eyebrow">Learning resources</p><h1>{{ documentType }}s</h1><p>Browse published {{ documentType.toLowerCase() }} files by course, academic year, and semester.</p></div><span v-if="!loading" class="count-pill">{{ courses.length }} courses</span></div><form class="filter-bar" @submit.prevent="search"><input v-model="query" type="search" :placeholder="`Search ${documentType.toLowerCase()}s`" /><button class="button button--primary" :disabled="searching">{{ searching ? 'Searching...' : 'Search' }}</button></form><p v-if="error" class="form-error">{{ error }}</p><div v-if="loading" class="loading-state">Loading courses...</div><template v-else><div v-if="searched && results.length" class="request-list"><article v-for="document in results" :key="document.id" class="request-card"><div class="request-card__main"><span class="status status--approved">{{ document.documentType }}</span><h2>{{ document.title }}</h2><p>{{ document.courseCode }} · {{ document.academicYear }} · Semester {{ document.semester }}</p></div><div class="table-actions"><button class="button button--ghost" @click="view(document)">View</button><button class="button button--primary" @click="download(document)">Download</button></div></article></div><div v-else-if="searched" class="empty-state"><h2>No {{ documentType.toLowerCase() }} files found</h2></div><div class="catalog-grid"><article v-for="course in courses" :key="course.id" class="material-card"><div class="material-card__top"><span class="material-type">{{ course.code }}</span><span>{{ course.documentCount }} {{ documentType }} files</span></div><h2>{{ course.name }}</h2><p>{{ course.description }}</p><RouterLink class="button button--primary" :to="`${basePath}/${course.id}`">View</RouterLink></article></div><div v-if="!courses.length && !searched" class="empty-state"><h2>No {{ documentType.toLowerCase() }} files found</h2><button class="button button--ghost" @click="loadCourses">Retry</button></div></template></section></template>
