<script setup>
import { onMounted, ref } from 'vue'
import { useAuthStore } from '@/stores/authStore'
import { documentApi } from '@/services/document.service'
const auth = useAuthStore(); const courses = ref([]); const loading = ref(true); const error = ref('')
async function load() { loading.value = true; error.value = ''; try { courses.value = await documentApi.courses() } catch { error.value = 'โหลดรายวิชาไม่สำเร็จ กรุณาลองใหม่' } finally { loading.value = false } }
onMounted(load)
</script>
<template><div class="home"><section class="page-panel home-hero-panel"><div class="home-hero__copy"><p class="eyebrow">Collaborative academic knowledge</p><h1>ความรู้ดี ๆ เริ่มจากการแบ่งปัน</h1><p>สวัสดี {{ auth.user?.displayName || auth.user?.username }} — เลือกรายวิชา หรือค้นหาเอกสารและผู้แบ่งปันได้ทันที</p><div class="hero-actions"><RouterLink class="button button--primary" to="/dashboard/search">ค้นหาในคลังความรู้</RouterLink><RouterLink class="button button--ghost" to="/dashboard/upload">แบ่งปันเอกสาร</RouterLink></div></div><div class="hero-note"><span>COMMUNITY LOOP</span><strong>ค้นพบ · ใช้งาน · ขอบคุณ · แบ่งปันต่อ</strong><p>ทุกยอดใช้งานที่มีคุณภาพช่วยสร้าง Recognition ให้ผู้แบ่งปัน</p></div></section><p v-if="error" class="form-error" role="alert">{{ error }}</p><div v-if="loading" class="loading-state skeleton-list" aria-label="กำลังโหลดรายวิชา"><div class="skeleton-line"></div><div class="skeleton-line"></div></div><section v-else class="page-panel"><div class="panel__header"><div><p class="eyebrow">Explore by course</p><h2>สำรวจตามรายวิชา</h2><p>เลือกวิชา แล้วไล่ดูปีการศึกษาและภาคเรียนจากข้อมูลที่มีจริง</p></div><span class="count-pill">{{ courses.length }} วิชา</span></div><div v-if="courses.length" class="catalog-grid"><article v-for="(course, index) in courses" :key="course.id" class="material-card" :class="`accent-card-${index % 4}`"><div class="material-card__top"><span class="material-type">{{ course.code }}</span><span class="material-meta">{{ course.documentCount }} เอกสาร</span></div><h3>{{ course.name }}</h3><p>{{ course.description || 'คลังเอกสารประกอบรายวิชา' }}</p><RouterLink class="text-link" :to="`/dashboard/courses/${course.id}`">ดูรายวิชา →</RouterLink></article></div><div v-else class="empty-state"><h2>ยังไม่มีรายวิชา</h2><p>เมื่อมีเอกสารที่เผยแพร่ รายวิชาจะปรากฏที่นี่</p><button class="button button--ghost" @click="load">ลองอีกครั้ง</button></div></section></div></template>
