<script setup>
import { computed, onMounted, ref } from 'vue'
import { adminApi } from '@/services/admin.service'
import { sheetApi } from '@/services/sheet.service'
import StatusBadge from '@/components/shared/StatusBadge.vue'
const active = ref('teachers'); const loading = ref(true); const busy = ref(''); const error = ref(''); const feedback = ref('')
const metadata = ref({ courses: [], academicYears: [], semesters: ['1','2'] }); const teachers = ref([]); const offerings = ref([]); const suggestions = ref([]); const teacherSearch = ref('')
const selectedTeacherOfferings = ref([])
const teacherForm = ref({ id:'', name:'', email:'', active:true }); const offeringForm = ref({ courseId:'', academicYear:'', semester:'', section:'', teacherIds:[] }); const suggestionStatus = ref('PENDING'); const rejectionReasons = ref({})
const shownTeachers = computed(() => { const q=teacherSearch.value.toLocaleLowerCase().trim(); return teachers.value.filter(t=>!q||`${t.name} ${t.email}`.toLocaleLowerCase().includes(q)) })
async function load(){loading.value=true;error.value='';try{const [meta,t,o,s]=await Promise.all([sheetApi.metadata(),adminApi.teachers(),adminApi.offerings(),adminApi.teacherSuggestions(suggestionStatus.value)]);metadata.value=meta;teachers.value=t.teachers;offerings.value=o.offerings;suggestions.value=s.suggestions}catch(caught){error.value=caught.message}finally{loading.value=false}}
onMounted(load)
async function editTeacher(teacher){teacherForm.value={id:teacher.id,name:teacher.name,email:teacher.email,active:teacher.active};try{selectedTeacherOfferings.value=(await adminApi.teacherOfferings(teacher.id)).offerings}catch(caught){error.value=caught.message}}
function clearTeacher(){teacherForm.value={id:'',name:'',email:'',active:true};selectedTeacherOfferings.value=[]}
async function saveTeacher(){busy.value='teacher';error.value='';feedback.value='';try{if(teacherForm.value.id)await adminApi.updateTeacher(teacherForm.value.id,teacherForm.value);else await adminApi.createTeacher(teacherForm.value);feedback.value='บันทึกข้อมูลอาจารย์แล้ว';clearTeacher();await load()}catch(caught){error.value=caught.message}finally{busy.value=''}}
function editOffering(offering){offeringForm.value={courseId:offering.courseId,academicYear:offering.academicYear,semester:offering.semester,section:offering.section,teacherIds:offering.teachers.map(t=>t.id)};active.value='offerings'}
async function saveOffering(){busy.value='offering';error.value='';feedback.value='';try{await adminApi.saveOffering(offeringForm.value);feedback.value='บันทึกรายวิชาที่เปิดสอนแล้ว';offeringForm.value={courseId:'',academicYear:'',semester:'',section:'',teacherIds:[]};await load()}catch(caught){error.value=caught.message}finally{busy.value=''}}
async function loadSuggestions(){busy.value='suggestions';try{suggestions.value=(await adminApi.teacherSuggestions(suggestionStatus.value)).suggestions}catch(caught){error.value=caught.message}finally{busy.value=''}}
async function decide(item,decision){const reason=rejectionReasons.value[item.id]||'';if(decision==='REJECT'&&!reason.trim()){error.value='กรุณาระบุเหตุผลที่ปฏิเสธ';return}busy.value=item.id;error.value='';try{await adminApi.decideTeacherSuggestion(item.id,decision,reason);feedback.value=decision==='APPROVE_GLOBAL'?'อนุมัติและอัปเดตฐานข้อมูลผู้สอนแล้ว':decision==='APPROVE_DOCUMENT'?'อนุมัติเฉพาะเอกสารแล้ว':'ปฏิเสธคำแนะนำแล้ว';await load()}catch(caught){error.value=caught.message}finally{busy.value=''}}
</script>
<template>
  <section class="page-panel"><div class="panel__header"><div><p class="eyebrow">Academic structure</p><h1>รายวิชาและผู้สอน</h1><p>จัดการอาจารย์ รายวิชาที่เปิดสอน และคำแนะนำจากผู้ใช้</p></div></div>
    <div class="request-tabs" role="tablist" aria-label="จัดการข้อมูลการศึกษา"><button v-for="tab in [{id:'teachers',label:'จัดการอาจารย์'},{id:'offerings',label:'รายวิชาที่เปิดสอน'},{id:'suggestions',label:'คำขอเพิ่มอาจารย์'}]" :key="tab.id" class="tab-button" :class="{'tab-button--active':active===tab.id}" role="tab" :aria-selected="active===tab.id" @click="active=tab.id">{{ tab.label }}</button></div>
    <p v-if="feedback" class="form-success" role="status">{{ feedback }}</p><p v-if="error" class="form-error" role="alert">{{ error }}</p><div v-if="loading" class="loading-state skeleton-list"><div class="skeleton-line"/><div class="skeleton-line"/></div>
    <template v-else>
      <section v-if="active==='teachers'" class="admin-academic-grid"><div><form class="form content-section" @submit.prevent="saveTeacher"><h2>{{ teacherForm.id?'แก้ไขอาจารย์':'เพิ่มอาจารย์' }}</h2><label>ชื่ออาจารย์<input v-model="teacherForm.name" required minlength="2" maxlength="120" /></label><label>Email (optional)<input v-model="teacherForm.email" type="email" maxlength="254" /></label><label class="checkbox-row"><input v-model="teacherForm.active" type="checkbox" /> เปิดใช้งาน</label><div class="table-actions"><button class="button button--primary" :disabled="Boolean(busy)">บันทึก</button><button v-if="teacherForm.id" class="button button--ghost" type="button" @click="clearTeacher">ยกเลิก</button></div></form><section v-if="teacherForm.id" class="content-section"><h3>รายวิชาที่สอน</h3><p v-if="!selectedTeacherOfferings.length" class="material-meta">ยังไม่มีรายวิชาที่เชื่อมโยง</p><ul class="instructor-list"><li v-for="offering in selectedTeacherOfferings" :key="offering.id">{{ offering.courseCode }} · {{ offering.courseName }} — {{ offering.academicYear }}/{{ offering.semester }}<span v-if="offering.section"> Sec. {{ offering.section }}</span></li></ul></section></div><section><div class="section-heading"><h2>อาจารย์</h2><span class="count-pill">{{ teachers.length }}</span></div><label>ค้นหา<input v-model="teacherSearch" type="search" placeholder="ชื่อหรืออีเมล" /></label><div class="request-list"><article v-for="teacher in shownTeachers" :key="teacher.id" class="request-card"><div><h3>{{ teacher.name }}</h3><p>{{ teacher.email||'ไม่มีอีเมล' }} · {{ teacher.active?'เปิดใช้งาน':'ปิดใช้งาน' }}</p></div><button class="button button--ghost button--small" @click="editTeacher(teacher)">แก้ไข</button></article></div></section></section>
      <section v-else-if="active==='offerings'" class="admin-academic-grid"><form class="form content-section" @submit.prevent="saveOffering"><h2>กำหนดรายวิชาที่เปิดสอน</h2><label>ปีการศึกษา<select v-model="offeringForm.academicYear" required><option value="" disabled>เลือกปี</option><option v-for="year in metadata.academicYears" :key="year">{{ year }}</option></select></label><label>ภาคเรียน<select v-model="offeringForm.semester" required><option value="" disabled>เลือกภาคเรียน</option><option v-for="term in metadata.semesters" :key="term">{{ term }}</option></select></label><label>รายวิชา<select v-model="offeringForm.courseId" required><option value="" disabled>เลือกรายวิชา</option><option v-for="course in metadata.courses" :key="course.id" :value="course.id">{{ course.code }} - {{ course.nameEn }}</option></select></label><label>Section (optional)<input v-model="offeringForm.section" maxlength="20" /></label><fieldset><legend>อาจารย์ผู้สอน (เลือกได้หลายคน)</legend><label v-for="teacher in teachers.filter(item=>item.active)" :key="teacher.id" class="checkbox-row"><input v-model="offeringForm.teacherIds" type="checkbox" :value="teacher.id" /> {{ teacher.name }}</label><p v-if="!teachers.some(item=>item.active)" class="material-meta">เพิ่มอาจารย์ที่เปิดใช้งานก่อน</p></fieldset><button class="button button--primary" :disabled="Boolean(busy)">บันทึก</button></form><section><div class="section-heading"><h2>รายการเปิดสอน</h2><span class="count-pill">{{ offerings.length }}</span></div><div v-if="!offerings.length" class="empty-state">ยังไม่มีข้อมูลรายวิชาที่เปิดสอน</div><div class="request-list"><article v-for="offering in offerings" :key="offering.id" class="request-card"><div><h3>{{ offering.courseCode }} · {{ offering.courseName }}</h3><p>ปี {{ offering.academicYear }} · ภาคเรียน {{ offering.semester }}<span v-if="offering.section"> · Section {{ offering.section }}</span></p><p>{{ offering.teachers.map(t=>t.name).join(', ')||'ยังไม่กำหนดผู้สอน' }}</p></div><button class="button button--ghost button--small" @click="editOffering(offering)">แก้ไข</button></article></div></section></section>
      <section v-else><div class="section-heading"><h2>คำขอเพิ่มข้อมูลอาจารย์</h2><label>สถานะ<select v-model="suggestionStatus" @change="loadSuggestions"><option>PENDING</option><option>APPROVED</option><option>REJECTED</option><option value="">ทั้งหมด</option></select></label></div><div v-if="!suggestions.length" class="empty-state">ไม่มีคำแนะนำในสถานะนี้</div><div class="request-list"><article v-for="item in suggestions" :key="item.id" class="request-card"><div class="request-card__main"><StatusBadge :value="item.status"/><h3>{{ item.teacherName }}</h3><p>{{ item.courseCode }} · {{ item.courseName }}</p><p>ปี {{ item.academicYear }} · ภาคเรียน {{ item.semester }}<span v-if="item.section"> · Section {{ item.section }}</span> · เสนอโดย @{{ item.submittedByUsername }}</p><p v-if="item.note">รายละเอียด: {{ item.note }}</p><p class="material-meta">{{ item.suggestionType==='EXISTING_TEACHER_NEW_ASSIGNMENT'?'มีอาจารย์ในระบบแล้ว แต่ยังไม่ผูกกับรายวิชานี้':'อาจารย์ใหม่' }}</p><label v-if="item.status==='PENDING'">เหตุผลกรณีปฏิเสธ<textarea v-model="rejectionReasons[item.id]" maxlength="500" rows="2" /></label></div><div v-if="item.status==='PENDING'" class="table-actions"><button class="button button--danger" :disabled="Boolean(busy)" @click="decide(item,'REJECT')">ไม่อนุมัติ</button><button class="button button--ghost" :disabled="Boolean(busy)" @click="decide(item,'APPROVE_DOCUMENT')">อนุมัติเฉพาะเอกสาร</button><button class="button button--primary" :disabled="Boolean(busy)" @click="decide(item,'APPROVE_GLOBAL')">อนุมัติและอัปเดตฐานข้อมูล</button></div></article></div></section>
    </template>
  </section>
</template>
