<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useAuthStore } from '@/stores/authStore'
import { contributorApi } from '@/services/contributor.service'
import { PROGRAM_OPTIONS, cohortOptions, programName } from '@/services/communityIdentity'
import AvatarEditor from '@/components/user/profile/AvatarEditor.vue'
const auth = useAuthStore(); const data = ref(null); const busy = ref(false); const error = ref(''); const success = ref(''); const avatarMenu = ref(false); const cropFile = ref(null); const uploadInput = ref()
const profile = reactive({ displayName:'', bio:'' }); const privacy = reactive({ profilePublic:true, showProgram:true, showCohort:true }); const notifications = reactive({ newFollower:true, followedDocuments:true, documentActivity:true, activityEmail:false }); const change = reactive({ category:'PROGRAM', requestedValue:'', reason:'' })
const nextDate = computed(() => data.value?.profile.nextDisplayNameChangeAt && new Date(data.value.profile.nextDisplayNameChangeAt)); const nameLocked = computed(() => nextDate.value && nextDate.value > new Date())
async function load() { data.value = await contributorApi.settings(); Object.assign(profile,data.value.profile); Object.assign(privacy,data.value.profile); Object.assign(notifications,data.value.notifications) }
async function run(action) { busy.value=true; error.value=''; success.value=''; try { await action(); success.value='บันทึกเรียบร้อย'; await auth.refresh(); await load() } catch(caught){ error.value=caught.message } finally { busy.value=false } }
const saveProfile=()=>run(()=>contributorApi.edit(profile)); const saveOptions=()=>run(()=>contributorApi.saveSettings({privacy,notifications}))
async function requestChange(){ if(!window.confirm('ยืนยันการส่งคำขอให้ผู้ดูแลตรวจสอบ?')) return; await run(()=>contributorApi.requestChange(change)); change.requestedValue='';change.reason='' }
function selectAvatar(event){ const file=event.target.files?.[0]; event.target.value=''; if(!file)return; if(file.size>1024*1024){error.value='Please upload a picture smaller than 1 MB.';return} if(!['image/jpeg','image/png','image/webp'].includes(file.type)){error.value='Please upload a valid PNG, JPEG, or WebP image.';return} cropFile.value=file;avatarMenu.value=false }
const saveAvatar=(fileData)=>run(async()=>{await contributorApi.uploadAvatar(fileData);cropFile.value=null}); const removeAvatar=()=>run(async()=>{await contributorApi.removeAvatar();avatarMenu.value=false})
onMounted(()=>load().catch(caught=>error.value=caught.message))
</script>
<template><section class="page-panel settings-page"><aside class="settings-nav"><h1>Settings</h1><a href="#public-profile">Public Profile</a><a href="#account">Account</a><a href="#privacy">Privacy</a><a href="#notifications">Notifications</a><a href="#password">Password & Authentication</a></aside><main v-if="data" class="settings-content"><p v-if="error" class="form-error" role="alert">{{ error }}</p><p v-if="success" class="form-success" role="status">{{ success }}</p>
<section id="public-profile" class="settings-section"><h2>Public Profile</h2><div class="avatar-setting"><img v-if="data.profile.avatarUrl" :src="data.profile.avatarUrl" alt="Current avatar" /><div v-else class="document-profile__avatar--fallback">{{ profile.displayName.slice(0,1) }}</div><div><button class="button button--ghost" @click="avatarMenu=!avatarMenu">Edit</button><div v-if="avatarMenu" class="avatar-menu"><button @click="uploadInput.click()">Upload a photo...</button><button @click="removeAvatar">Remove photo</button></div><input ref="uploadInput" hidden type="file" accept="image/png,image/jpeg,image/webp" @change="selectAvatar" /></div></div><AvatarEditor v-if="cropFile" :file="cropFile" :busy="busy" @save="saveAvatar" @cancel="cropFile=null" /><form class="form" @submit.prevent="saveProfile"><label>Display Name<input v-model="profile.displayName" maxlength="100" required :disabled="nameLocked" /><small v-if="nameLocked">เปลี่ยนได้อีกครั้งวันที่ {{ nextDate.toLocaleDateString('th-TH') }}</small></label><label>Bio<textarea v-model="profile.bio" maxlength="300" rows="4" /></label><button class="button button--primary" :disabled="busy">Save profile</button></form></section>
<section id="account" class="settings-section"><h2>Account</h2><dl class="metadata-list"><div><dt>Email</dt><dd>{{ data.account.email }}</dd></div><div><dt>Role</dt><dd>{{ data.account.role }}</dd></div><div><dt>Email verified</dt><dd>{{ data.account.emailVerified ? 'Verified' : 'Not verified' }}</dd></div><div><dt>สาขาปัจจุบัน</dt><dd>{{ programName(data.profile.program) }}</dd></div><div><dt>รุ่นปัจจุบัน</dt><dd>{{ data.profile.cohort }}</dd></div></dl><form class="form" @submit.prevent="requestChange"><label>ประเภทคำขอ<select v-model="change.category"><option value="PROGRAM">ต้องการเปลี่ยนสาขา</option><option value="COHORT">ต้องการเปลี่ยนรุ่น</option></select></label><label>ค่าที่ต้องการ<select v-if="change.category==='PROGRAM'" v-model="change.requestedValue" required><option value="" disabled>เลือกสาขา</option><option v-for="item in PROGRAM_OPTIONS" :key="item.value" :value="item.value">{{ item.label }}</option></select><select v-else v-model="change.requestedValue" required><option value="" disabled>เลือกรุ่น</option><option v-for="item in cohortOptions()" :key="item" :value="item">รุ่น {{ item }}</option></select></label><label>เหตุผล<textarea v-model="change.reason" minlength="5" maxlength="500" required /></label><button class="button button--ghost" :disabled="busy">ส่งคำขอให้ผู้ดูแล</button></form><h3>Request history</h3><div v-if="!data.changeRequests.length" class="empty-state">ยังไม่มีคำขอ</div><article v-for="request in data.changeRequests" :key="request.id" class="settings-request"><strong>{{ request.category }}: {{ request.current_value }} → {{ request.requested_value }}</strong><span class="type-chip">{{ request.status }}</span><p>{{ request.reason }}</p><p v-if="request.decision_reason">Admin: {{ request.decision_reason }}</p></article></section>
<section id="privacy" class="settings-section"><h2>Privacy</h2><label><input v-model="privacy.profilePublic" type="checkbox" /> Public profile</label><label><input v-model="privacy.showProgram" type="checkbox" /> Show program</label><label><input v-model="privacy.showCohort" type="checkbox" /> Show cohort</label></section><section id="notifications" class="settings-section"><h2>Notifications</h2><label><input v-model="notifications.newFollower" type="checkbox" /> New followers</label><label><input v-model="notifications.followedDocuments" type="checkbox" /> New documents from followed users</label><label><input v-model="notifications.documentActivity" type="checkbox" /> Document activity</label><label><input v-model="notifications.activityEmail" type="checkbox" /> Optional activity email</label><button class="button button--primary" :disabled="busy" @click="saveOptions">Save preferences</button></section><section id="password" class="settings-section"><h2>Password & Authentication</h2><p>Use the secure password reset flow to change a forgotten password.</p><RouterLink class="button button--ghost" to="/forgot-password">Reset password</RouterLink></section></main></section></template>
